Import upstream bacula version 1.38.11

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4401,7 +4401,7 @@ else
   HAVE_SUN_OS_TRUE='#'
   HAVE_SUN_OS_FALSE=
 fi
-        cat >>confdefs.h <<\_ACEOF
+	cat >>confdefs.h <<\_ACEOF
 #define HAVE_SUN_OS 1
 _ACEOF
 
@@ -4428,7 +4428,7 @@ else
   HAVE_OSF1_OS_TRUE='#'
   HAVE_OSF1_OS_FALSE=
 fi
-        cat >>confdefs.h <<\_ACEOF
+	cat >>confdefs.h <<\_ACEOF
 #define HAVE_OSF1_OS 1
 _ACEOF
 
@@ -4455,7 +4455,7 @@ else
   HAVE_AIX_OS_TRUE='#'
   HAVE_AIX_OS_FALSE=
 fi
-        cat >>confdefs.h <<\_ACEOF
+	cat >>confdefs.h <<\_ACEOF
 #define HAVE_AIX_OS 1
 _ACEOF
 
@@ -4482,7 +4482,7 @@ else
   HAVE_HPUX_OS_TRUE='#'
   HAVE_HPUX_OS_FALSE=
 fi
-        cat >>confdefs.h <<\_ACEOF
+	cat >>confdefs.h <<\_ACEOF
 #define HAVE_HPUX_OS 1
 _ACEOF
 
@@ -4509,7 +4509,7 @@ else
   HAVE_LINUX_OS_TRUE='#'
   HAVE_LINUX_OS_FALSE=
 fi
-        cat >>confdefs.h <<\_ACEOF
+	cat >>confdefs.h <<\_ACEOF
 #define HAVE_LINUX_OS 1
 _ACEOF
 
@@ -4536,7 +4536,7 @@ else
   HAVE_FREEBSD_OS_TRUE='#'
   HAVE_FREEBSD_OS_FALSE=
 fi
-        cat >>confdefs.h <<\_ACEOF
+	cat >>confdefs.h <<\_ACEOF
 #define HAVE_FREEBSD_OS 1
 _ACEOF
 
@@ -4563,7 +4563,7 @@ else
   HAVE_NETBSD_OS_TRUE='#'
   HAVE_NETBSD_OS_FALSE=
 fi
-        cat >>confdefs.h <<\_ACEOF
+	cat >>confdefs.h <<\_ACEOF
 #define HAVE_NETBSD_OS 1
 _ACEOF
 
@@ -4590,7 +4590,7 @@ else
   HAVE_OPENBSD_OS_TRUE='#'
   HAVE_OPENBSD_OS_FALSE=
 fi
-        cat >>confdefs.h <<\_ACEOF
+	cat >>confdefs.h <<\_ACEOF
 #define HAVE_OPENBSD_OS 1
 _ACEOF
 
@@ -4617,7 +4617,7 @@ else
   HAVE_BSDI_OS_TRUE='#'
   HAVE_BSDI_OS_FALSE=
 fi
-        cat >>confdefs.h <<\_ACEOF
+	cat >>confdefs.h <<\_ACEOF
 #define HAVE_BSDI_OS 1
 _ACEOF
 
@@ -4644,7 +4644,7 @@ else
   HAVE_SGI_OS_TRUE='#'
   HAVE_SGI_OS_FALSE=
 fi
-        cat >>confdefs.h <<\_ACEOF
+	cat >>confdefs.h <<\_ACEOF
 #define HAVE_SGI_OS 1
 _ACEOF
 
@@ -4660,7 +4660,7 @@ else
 fi
 fi
 
-if test $HAVE_UNAME=yes -a x`uname -s` = xIRIX
+if test $HAVE_UNAME=yes -a x`uname -s` = xIRIX -o x`uname -s` = xIRIX64
 then
 
 
@@ -4671,7 +4671,7 @@ else
   HAVE_IRIX_OS_TRUE='#'
   HAVE_IRIX_OS_FALSE=
 fi
-        cat >>confdefs.h <<\_ACEOF
+	cat >>confdefs.h <<\_ACEOF
 #define HAVE_IRIX_OS 1
 _ACEOF
 
@@ -4724,70 +4724,70 @@ then
         echo "distname set to $DISTNAME"
 elif test $HAVE_UNAME=yes -a x`uname -s` = xOSF1
 then
-        DISTNAME=alpha
+	DISTNAME=alpha
 elif test $HAVE_UNAME=yes -a x`uname -s` = xAIX
 then
-        DISTNAME=aix
+	DISTNAME=aix
 elif test $HAVE_UNAME=yes -a x`uname -s` = xHP-UX
 then
-        DISTNAME=hpux
+	DISTNAME=hpux
 elif test $HAVE_UNAME=yes -a x`uname -s` = xSunOS
 then
-        DISTNAME=solaris
+	DISTNAME=solaris
 elif test $HAVE_UNAME=yes -a x`uname -s` = xFreeBSD
 then
-        DISTNAME=freebsd
+	DISTNAME=freebsd
 elif test $HAVE_UNAME=yes -a x`uname -s` = xNetBSD
 then
-        DISTNAME=netbsd
+	DISTNAME=netbsd
 elif test $HAVE_UNAME=yes -a x`uname -s` = xOpenBSD
 then
-        DISTNAME=openbsd
+	DISTNAME=openbsd
 elif test $HAVE_UNAME=yes -a x`uname -s` = xIRIX
 then
-        DISTNAME=irix
+	DISTNAME=irix
 elif test $HAVE_UNAME=yes -a x`uname -s` = xBSD/OS
 then
-        DISTNAME=bsdi
+	DISTNAME=bsdi
 elif test -f /etc/SuSE-release
 then
-        DISTNAME=suse
+	DISTNAME=suse
 elif test -d /etc/SuSEconfig
 then
-        DISTNAME=suse5
+	DISTNAME=suse5
 elif test -f /etc/mandrake-release
 then
-        DISTNAME=mandrake
+	DISTNAME=mandrake
 elif test -f /etc/whitebox-release
 then
        DISTNAME=redhat
 elif test -f /etc/redhat-release
 then
-        DISTNAME=redhat
+	DISTNAME=redhat
 elif test -f /etc/gentoo-release
 then
-        DISTNAME=gentoo
+	DISTNAME=gentoo
 elif test -f /etc/debian_version
 then
-        DISTNAME=debian
+	DISTNAME=debian
 elif test -f /etc/slackware-version
 then
-        DISTNAME=slackware
+	DISTNAME=slackware
 elif test $HAVE_UNAME=yes -a x`uname -s` = xDarwin
 then
     DISTNAME=darwin
 elif test -f /etc/engarde-version
 then
-        DISTNAME=engarde
+	DISTNAME=engarde
 elif test "$CYGWIN" = yes
 then
-        DISTNAME=cygwin
-        cat >>confdefs.h <<\_ACEOF
+	DISTNAME=cygwin
+	cat >>confdefs.h <<\_ACEOF
 #define HAVE_CYGWIN 1
 _ACEOF
 
 else
-        DISTNAME=unknown
+	DISTNAME=unknown
 fi
 echo "$as_me:$LINENO: result: done" >&5
 echo "${ECHO_T}done" >&6
@@ -17468,7 +17468,7 @@ ac_x_header_dirs='
 /usr/openwin/share/include'
 
 if test "$ac_x_includes" = no; then
-  # Guess where to find include files, by looking for Intrinsic.h.
+  # Guess where to find include files, by looking for Xlib.h.
   # First, try using that file with no special directory specified.
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -17476,7 +17476,7 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <X11/Intrinsic.h>
+#include <X11/Xlib.h>
 _ACEOF
 if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
@@ -17503,7 +17503,7 @@ else
 sed 's/^/| /' conftest.$ac_ext >&5
 
   for ac_dir in $ac_x_header_dirs; do
-  if test -r "$ac_dir/X11/Intrinsic.h"; then
+  if test -r "$ac_dir/X11/Xlib.h"; then
     ac_x_includes=$ac_dir
     break
   fi
@@ -17524,11 +17524,11 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <X11/Intrinsic.h>
+#include <X11/Xlib.h>
 int
 main ()
 {
-XtMalloc (0)
+XrmInitialize ()
   ;
   return 0;
 }
@@ -21280,60 +21280,11 @@ _ACEOF
 
 
 
-echo "$as_me:$LINENO: checking for type of signal functions" >&5
+  echo "$as_me:$LINENO: checking for type of signal functions" >&5
 echo $ECHO_N "checking for type of signal functions... $ECHO_C" >&6
-if test "${bash_cv_signal_vintage+set}" = set; then
+  if test "${bash_cv_signal_vintage+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-
-  cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <signal.h>
-int
-main ()
-{
-
-    sigset_t ss;
-    struct sigaction sa;
-    sigemptyset(&ss); sigsuspend(&ss);
-    sigaction(SIGINT, &sa, (struct sigaction *) 0);
-    sigprocmask(SIG_BLOCK, &ss, (sigset_t *) 0);
-
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  bash_cv_signal_vintage=posix
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
 
     cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -21346,8 +21297,11 @@ int
 main ()
 {
 
-        int mask = sigmask(SIGINT);
-        sigsetmask(mask); sigblock(mask); sigpause(mask);
+      sigset_t ss;
+      struct sigaction sa;
+      sigemptyset(&ss); sigsuspend(&ss);
+      sigaction(SIGINT, &sa, (struct sigaction *) 0);
+      sigprocmask(SIG_BLOCK, &ss, (sigset_t *) 0);
 
   ;
   return 0;
@@ -21375,7 +21329,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  bash_cv_signal_vintage=4.2bsd
+  bash_cv_signal_vintage="posix"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
@@ -21387,16 +21341,13 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-
-        #include <signal.h>
-        RETSIGTYPE foo() { }
+#include <signal.h>
 int
 main ()
 {
 
-                int mask = sigmask(SIGINT);
-                sigset(SIGINT, foo); sigrelse(SIGINT);
-                sighold(SIGINT); sigpause(SIGINT);
+	  int mask = sigmask(SIGINT);
+	  sigsetmask(mask); sigblock(mask); sigpause(mask);
 
   ;
   return 0;
@@ -21424,12 +21375,61 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  bash_cv_signal_vintage=svr3
+  bash_cv_signal_vintage="4.2bsd"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-bash_cv_signal_vintage=v7
+
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+	  #include <signal.h>
+	  RETSIGTYPE foo() { }
+int
+main ()
+{
+
+		  int mask = sigmask(SIGINT);
+		  sigset(SIGINT, foo); sigrelse(SIGINT);
+		  sighold(SIGINT); sigpause(SIGINT);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  bash_cv_signal_vintage="svr3"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+bash_cv_signal_vintage="v7"
 
 fi
 rm -f conftest.err conftest.$ac_objext \
@@ -21445,24 +21445,24 @@ rm -f conftest.err conftest.$ac_objext \
 
 fi
 
-echo "$as_me:$LINENO: result: $bash_cv_signal_vintage" >&5
+  echo "$as_me:$LINENO: result: $bash_cv_signal_vintage" >&5
 echo "${ECHO_T}$bash_cv_signal_vintage" >&6
-if test "$bash_cv_signal_vintage" = posix; then
-cat >>confdefs.h <<\_ACEOF
+  if test "$bash_cv_signal_vintage" = "posix"; then
+    cat >>confdefs.h <<\_ACEOF
 #define HAVE_POSIX_SIGNALS 1
 _ACEOF
 
-elif test "$bash_cv_signal_vintage" = "4.2bsd"; then
-cat >>confdefs.h <<\_ACEOF
+  elif test "$bash_cv_signal_vintage" = "4.2bsd"; then
+    cat >>confdefs.h <<\_ACEOF
 #define HAVE_BSD_SIGNALS 1
 _ACEOF
 
-elif test "$bash_cv_signal_vintage" = svr3; then
-cat >>confdefs.h <<\_ACEOF
+  elif test "$bash_cv_signal_vintage" = "svr3"; then
+    cat >>confdefs.h <<\_ACEOF
 #define HAVE_USG_SIGHOLD 1
 _ACEOF
 
-fi
+  fi
 
 echo "$as_me:$LINENO: checking for mode_t" >&5
 echo $ECHO_N "checking for mode_t... $ECHO_C" >&6
