Imported Upstream version 5.0.0

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -20,8 +20,8 @@ dummy:
 
 # --client-only directories
 fd_subdirs = src scripts src/lib src/findlib src/filed \
-       @READLINE_SRC@ @BAT_DIR@ @GNOME_DIR@ @TRAY_MONITOR_DIR@ @WX_DIR@ \
-       src/console src/plugins/fd
+       @READLINE_SRC@ @BAT_DIR@ @TRAY_MONITOR_DIR@ @WX_DIR@ \
+       src/console @FD_PLUGIN_DIR@
 
 # Non-client-only directores
 subdirs =    src/cats @DIRD_DIR@ @STORED_DIR@ src/tools
@@ -45,8 +45,8 @@ LIBTOOL_DEPS = @LIBTOOL_DEPS@
 all: Makefile
 	@for I in ${all_subdirs}; \
 	  do (cd $$I; echo "==>Entering directory `pwd`"; \
-	      $(MAKE) $@ || (echo ""; echo ""; echo "  ====== Error in `pwd` ======"; \
-			    echo ""; echo "";)); \
+	      $(MAKE) DESTDIR=$(DESTDIR) $@ || (echo ""; echo ""; echo "  ====== Error in `pwd` ======"; \
+			    echo ""; echo ""; exit 1;)); \
 	done
 
 depend:
@@ -56,8 +56,8 @@ depend:
 bacula-fd: Makefile	   
 	@for I in ${fd_subdirs}; \
 	  do (cd $$I; echo "==>Entering directory `pwd`"; \
-	      $(MAKE) all || (echo ""; echo ""; echo "	 ====== Error in `pwd` ======; \
-			    echo ""; echo "";)); \
+	      $(MAKE) DESTDIR=$(DESTDIR) all || (echo ""; echo ""; echo "   ====== Error in `pwd` ======; \
+			    echo ""; echo ""; exit 1;)); \
 	done
 
 #-------------------------------------------------------------------------
diff --git a/src/win32/Makefile b/src/win32/Makefile
--- a/src/win32/Makefile
+++ b/src/win32/Makefile
@@ -1,46 +1,36 @@
 ECHO_CMD=@
 
+WIN32_DIRS=lib filed filed/plugins console scripts
+
+WIN64_DIRS=lib filed filed/plugins console scripts
+
 ifeq ($(WIN64),yes)
- DIRS=	lib \
-	filed \
-	filed/plugins \
-	console \
-	scripts
-
-  INSTALLER=win64_installer
-
-  SPECIAL=bsmtp
+	 DIRS=$(WIN64_DIRS)
+	 INSTALLER=win64_installer
+	 SPECIAL=bsmtp
 else
- DIRS=	lib \
-	cats \
-	filed \
-	filed/plugins \
-	dird \
-	stored \
-	console \
-	wx-console \
-	tools \
-	scripts 
-
-  INSTALLER=win32_installer
-
-  SPECIAL=
+	 DIRS=$(WIN32_DIRS)
+	 INSTALLER=win32_installer
+	 SPECIAL=bat bsmtp
 endif
 
-.PHONY: $(DIRS) clean all Makefile.inc win32_installer newinstaller \
+.PHONY: $(DIRS) clean all Makefile.inc win32_installer full_win32_installer \
 	 win64_installer bsmtp
 
 all: Makefile.inc $(DIRS) $(SPECIAL) $(INSTALLER)
 
-clean: $(DIRS) win32_installer newinstaller win64_installer
+clean: $(DIRS) win32_installer win64_installer
 	$(ECHO_CMD)-rm -rf release32 release64
 
-newinstaller:
+bat:
+	(cd ../qt-console; ./make-win32)
+
+full_win32_installer:
 	@if test -f Makefile.inc; then \
 	   if $(MAKE) -C $@ $(MAKECMDGOALS); then \
 		echo "\n===== Make of $@ succeeded =====\n\n" ; \
 	   else  \
-		echo "\n!!!!! Make of $@ failed !!!!!\n\n" ; \
+		echo "\n!!!!! Make of $@ failed !!!!!\n\n" ; exit 1; \
 	   fi ; \
 	fi
 
@@ -49,7 +39,7 @@ win32_installer:
 	   if $(MAKE) -C $@ $(MAKECMDGOALS); then \
 		echo "\n===== Make of $@ succeeded =====\n\n" ; \
 	   else  \
-		echo "\n!!!!! Make of $@ failed !!!!!\n\n" ; \
+		echo "\n!!!!! Make of $@ failed !!!!!\n\n" ; exit 1; \
 	   fi ; \
 	fi
 
@@ -58,7 +48,7 @@ win64_installer:
 	   if $(MAKE) -C $@ $(MAKECMDGOALS); then \
 		echo "\n===== Make of $@ succeeded =====\n\n" ; \
 	   else  \
-		echo "\n!!!!! Make of $@ failed !!!!!\n\n" ; \
+		echo "\n!!!!! Make of $@ failed !!!!!\n\n" ; exit 1; \
 	   fi ; \
 	fi
 
@@ -68,7 +58,7 @@ $(DIRS):
 	   if $(MAKE) -C $@ $(MAKECMDGOALS); then \
 		echo "\n===== Make of $@ succeeded =====\n\n" ; \
 	   else  \
-		echo "\n!!!!! Make of $@ failed !!!!!\n\n" ; \
+		echo "\n!!!!! Make of $@ failed !!!!!\n\n" ; exit 1; \
 	   fi ; \
 	fi
 
@@ -77,7 +67,7 @@ bsmtp:
 	   if $(MAKE) -C tools bsmtp $(MAKECMDGOALS); then \
 		echo "\n===== Make of tools/bsmtp succeeded =====\n\n" ; \
 	   else  \
-		echo "\n!!!!! Make of tools/bsmtp failed !!!!!\n\n" ; \
+		echo "\n!!!!! Make of tools/bsmtp failed !!!!!\n\n" ; exit 1; \
 	   fi ; \
 	fi
 
