Imported bacula-2.2.6 Imported bacula-2.2.6 into Mercurial repository

diff --git a/autoconf/configure.in b/autoconf/configure.in
--- a/autoconf/configure.in
+++ b/autoconf/configure.in
@@ -74,6 +74,8 @@ AC_PATH_PROG(GROWISOFS, growisofs, growisofs)
 AC_PATH_PROG(DVDRWMEDIAINFO, dvd+rw-mediainfo, dvd+rw-mediainfo)
 AC_PATH_PROG(DVDRWFORMAT, dvd+rw-format, dvd+rw-format)
 AC_PATH_PROG(PKGCONFIG, pkg-config, pkg-config)
+AC_PATH_PROG(QMAKE, qmake, none)
+AC_PATH_PROG(QMAKEQT4, qmake-qt4, none)
 AC_ARG_VAR(WXCONFIG, [wx-config command. On some systems, you must set it to wx-config-2.6 to use wxWidgets 2.6.])
 if test "x$WXCONFIG" = x; then
   WXCONFIG=wx-config
@@ -2230,10 +2232,23 @@ AC_OUTPUT([autoconf/Make.common \
 )
 
 if test "${support_bat}" = "yes" ; then
+  if test "x$QMAKE" = "xnone" && test "x$QMAKEQT4" = "xnone"; then
+  echo "Could not find qmake or qmake-qt4 in $PATH. Check your Qt installation"
+  exit 1
+  fi
+
+  QMAKEBIN="qmake"
+
+  if test "x$QMAKEQT4" != "xnone"; then
+    QMAKEBIN=qmake-qt4
+  fi
+
+
+  
   cd src/qt-console
   chmod 755 install_conf_file build-depkgs-qt-console
-  echo "Creating bat Makefile"	
-  qmake
+  echo "Creating bat Makefile"
+  $QMAKEBIN
   cd ${BUILD_DIR}
 fi
 
