Imported Upstream version 5.2.3

diff --git a/examples/autochangers/chio-bacula b/examples/autochangers/chio-bacula
--- a/examples/autochangers/chio-bacula
+++ b/examples/autochangers/chio-bacula
@@ -29,6 +29,19 @@
 # The labels of the virtual barcode reader are located in the BARCODE_FILE
 SIMULATE_BARCODE=true
 BARCODE_FILE=/usr/local/etc/bacula-barcodes
+TMPDIR=/tmp
+
+make_temp_file() 
+{
+  TMPFILE=`mktemp ${TMPDIR}/mtx$1.XXXXXXXXXX 2> /dev/null`
+  if test $? -ne 0 || test x${TMPFILE} = x; then
+     TMPFILE="${TMPDIR}/mtx$1.$$"
+     if test -f ${TMPFILE}; then
+        echo "ERROR: Temp file security problem on: ${TMPFILE}"
+        exit 1
+     fi
+  fi
+}
 
 me=$(basename $0)
 
@@ -119,11 +132,12 @@ case ${COMMAND} in
 
     loaded)
         # echo "Request loaded"
-        ${MTX} -f ${CHANGER} status -S > /tmp/mtx.$$
+        make_temp_file
+        ${MTX} -f ${CHANGER} status -S > ${TMPFILE}
         rtn=$?
-        cat /tmp/mtx.$$ | grep "^drive ${DRIVE}: <FULL>" | awk '{print $6+1}' | tr -d ">"
-        cat /tmp/mtx.$$ | grep "^drive ${DRIVE}:  source: <>" | awk "{print 0}"
-        rm -f /tmp/mtx.$$
+        cat ${TMPFILE} | grep "^drive ${DRIVE}: <FULL>" | awk '{print $6+1}' | tr -d ">"
+        cat ${TMPFILE} | grep "^drive ${DRIVE}:  source: <>" | awk "{print 0}"
+        rm -f ${TMPFILE}
         exit $rtn
         ;;
 
diff --git a/examples/autochangers/locking-mtx-changer b/examples/autochangers/locking-mtx-changer
--- a/examples/autochangers/locking-mtx-changer
+++ b/examples/autochangers/locking-mtx-changer
@@ -35,6 +35,21 @@
 MTX=/lysator/bin/mtx
 LOCKDIR=/tmp
 
+TMPDIR=/tmp
+
+make_temp_file() 
+{
+  TMPFILE=`mktemp ${TMPDIR}/mtx$1.XXXXXXXXXX 2> /dev/null`
+  if test $? -ne 0 || test x${TMPFILE} = x; then
+     TMPFILE="${TMPDIR}/mtx$1.$$"
+     if test -f ${TMPFILE}; then
+        echo "ERROR: Temp file security problem on: ${TMPFILE}"
+        exit 1
+     fi
+  fi
+}
+
+
 if test $# -lt 2 ; then
   echo "usage: mtx-changer ctl-device command slot archive-device drive"
   echo "  Insufficient number of arguments arguments given."
@@ -64,14 +79,15 @@ wait_for_drive() {
 LOCKFILE="${LOCKDIR}/mtx-changer:`echo $ctl | tr / _'"
 
 changer_lock() {
-    echo "$$" >$LOCKFILE.$$
+	make_temp_file lock
+    echo "$$" >${TMPFILE}
     
-    while ! ln -n $LOCKFILE.$$ $LOCKFILE 2>/dev/null; do
+    while ! ln -n ${TMPFILE} $LOCKFILE 2>/dev/null; do
        echo "$0: changer lock busy, retrying in 30 seconds..."
        sleep 30
     done
 
-    rm $LOCKFILE.$$
+    rm ${TMPFILE}
 }
 
 changer_unlock() {
@@ -141,11 +157,12 @@ case $cmd in
       ;;
 
    loaded)
-      ${MTX} -f $ctl status >/tmp/mtx.$$
+	  make_temp_file
+      ${MTX} -f $ctl status >${TMPFILE}
       rtn=$?
-      cat /tmp/mtx.$$ | grep "^Data Transfer Element $drive:Full" | awk "{print \$7}"
-      cat /tmp/mtx.$$ | grep "^Data Transfer Element $drive:Empty" | awk "{print 0}"
-      rm -f /tmp/mtx.$$
+      cat ${TMPFILE} | grep "^Data Transfer Element $drive:Full" | awk "{print \$7}"
+      cat ${TMPFILE} | grep "^Data Transfer Element $drive:Empty" | awk "{print 0}"
+      rm -f ${TMPFILE}
       changer_unlock $ctl
       exit $rtn
       ;;
diff --git a/release/makebacularel b/release/makebacularel
--- a/release/makebacularel
+++ b/release/makebacularel
@@ -12,36 +12,46 @@
 # Commit all changes, update the language files, 
 #    export the release, make a release tar.
 #
-. ./functions
+# source config
+. ./config
 
-cwd=`pwd`
-reltype=release
 tagbase=Release-
 base_dir=bacula
 base_pkg=bacula
+
+remote=$2
+branch=$3
 ver=$4
+
 if [ $# != 4 ] ; then
   echo "Need $0 <source-directory> <remote-name> <branch> <version>"
-  echo "e.g. $0 release-source bee 4.0 4.0.1"
+  echo "e.g. $0 release-source bee Branch-4.0 4.0.3"
   exit 1
 fi
 cd $1
-check_return_code "$0: Directory $1 does not exist"
-cd bacula
-check_return_code "$0: Directory $1/bacula does not exist"
+if [ $? -ne 0 ]; then
+   echo "Directory: $1 does not exist"
+   exit 1
+fi
 src=`pwd` 
 current=`git branch | awk '/*/ { print $2 }'`
-remote=$2
-branch=$3
+cd $base_dir 
+if [ $?  -ne 0 ]; then
+   echo "Directory: $1 does not exist"
+   exit 1
+fi
 git checkout ${branch}
-check_return_code "$0: Checkout of branch ${branch} failed."
 git pull ${remote} ${branch}
+if [ $? -ne 0 ]; then
+   echo "Checkout of branch ${branch} failed."
+   exit 1
+fi
 fulltag=$tagbase$ver
 echo " "
-echo "$0: Making $reltype for $base_pkg-$ver ..."
+echo "Making $reltype for $base_pkg-$ver ..."
 echo " "
-echo "OK?  ctl-c to stop"
-read a
+#echo "OK?  ctl-c to stop"
+#read a
 rm -rf Release-$ver
 if [ $reltype != "beta" ] ; then
    cd src
@@ -55,14 +65,14 @@ if [ a$updatepo != ano ]; then
    cd po
    make update-po
    cd ${src}   
-   git commit -am "Final po changes for ${fulltag}"
 fi
-git tag -d ${fulltag} 2>/dev/null 1>/dev/null
+
+git tag -d ${fulltag}
 echo "Creating new tag -- $fulltag"
 git tag $fulltag
 if [ $? != 0 ] ; then
   echo " "
-  echo "makebacularel: Non-zero return status from Git"
+  echo "Non-zero return status from Git"
   echo " "
   exit 1
 fi
@@ -72,24 +82,31 @@ rm -rf $base_pkg-$ver $base_pkg-$ver.tar.gz $base_pkg-$ver.tar.gz.sig
 rm -rf $fulltag
 cd ${src}
 git archive --format=tar --prefix=$base_pkg-$ver/ $fulltag | gzip >${cwd}/$base_pkg-$ver.tar.gz
+
 if [ $? != 0 ] ; then
   echo " "
-  echo "makebacularel: Non-zero return status from Git"
+  echo "Non-zero return status from Git"
   echo " "
   exit 1
 fi
 echo "Exported release into ${cwd}/$base_pkg-$ver.tar.gz"
 cd ${cwd}
 tar xfz $base_pkg-$ver.tar.gz 
-cd $base_pkg-$ver/
+# First remove Enterprise Win32 plugin source
+cd $base_pkg-$ver/bacula
+cp -fp ReleaseNotes ${cwd}/ReleaseNotes
+
+cd ${cwd}/$base_pkg-$ver
+# Move directories to release names including version
 mv bacula $base_pkg-$ver
 mv gui $base_pkg-gui-$ver
 mv regress $base_pkg-regress-$ver
+# Tar each component individually
 tar cvfz ../$base_pkg-$ver.tar.gz $base_pkg-$ver
 tar cvfz ../$base_pkg-gui-$ver.tar.gz $base_pkg-gui-$ver
 tar cvfz ../$base_pkg-regress-$ver.tar.gz $base_pkg-regress-$ver
-rm -rf $base_pkg-$ver
 cd ..
+rm -rf $base_pkg-$ver
 ./sign $base_pkg-$ver.tar.gz
 ./sign $base_pkg-gui-$ver.tar.gz
 ./sign $base_pkg-regress-$ver.tar.gz
@@ -97,10 +114,9 @@ cd ..
 if [ a$push != ano ]; then
    cd ${src}
    git push ${remote} ${branch}
-#   git push ${remote} tag ${fulltag}
-   echo "Pushed ${remote}"
+   git push ${remote} tag ${fulltag}
+   echo "Pushed ${remote} and push tag ${fulltag}"
 fi
 
 cd ${src}
 git checkout ${current}
-exit 0
diff --git a/release/makedocsrel b/release/makedocsrel
--- a/release/makedocsrel
+++ b/release/makedocsrel
@@ -9,62 +9,86 @@
 #
 # Commit all changes, export the release, make a release tar.
 #
-. ./functions
+# source ./config
+. ./config
 
-cwd=`pwd`
-reltype=release
 tagbase=Release-
 base_dir=docs
 base_pkg=bacula-$base_dir
 remote=$3
 branch=$4
 ver=$5
+fulltag=$tagbase$ver
 
 if [ $# != 5 ] ; then
   echo "Need $0 <bacula-source-directory> <docs-source-directory> <remote-name> <branch> <version>"
-  echo "e.g. $0 bacula-source docs-source bee master 4.0.1"
+  echo "e.g. $0 bacula-source docs-source bee Branch-4.0 4.0.3"
   exit 1
 fi
-
-# Get Bacula branch setup
-cd $1/bacula
-check_return_code "$0: Directory $1/bacula does not exist"
-
+cd $1
+if [ $? -ne 0 ]; then
+   echo "Directory: $1 does not exist"
+   exit 1
+fi
+cd bacula
+if [ $?  -ne 0 ]; then
+   echo "Directory: $1 does not exist"
+   exit 1
+fi
 bcurrent=`git branch | awk '/*/ { print $2 }'`
 git checkout ${branch}
-check_return_code "$0: Checkout of branch ${branch} in $1/bacula failed."
+if [ $? -ne 0 ]; then
+   echo "Checkout of branch ${branch} in $1/bacula failed."
+   exit 1
+fi
 git pull ${remote} ${branch}
 bsrc=`pwd` 
 cd ${cwd}
-
-# Go to docs
-cd $2/$base_dir
-check_return_code "$0: Directory $2/$base_dir does not exist"
-
+cd $2
+if [ $? -ne 0 ]; then
+   echo "Directory: $2 does not exist"
+   exit 1
+fi
+cd $base_dir
+if [ $?  -ne 0 ]; then
+   echo "Directory: $2 does not exist"
+   exit 1
+fi
 current=`git branch | awk '/*/ { print $2 }'`
 src=`pwd` 
 git checkout ${branch}
-check_return_code "$0: Checkout of branch ${branch} in ${src} failed."
-
+if [ $? -ne 0 ]; then
+   echo "Checkout of branch ${branch} in ${src} failed."
+   exit 1
+fi
 git pull ${remote} ${branch}
-fulltag=$tagbase$ver
 echo " "
-echo "$0: Making $reltype for $base_pkg-$ver ..."
+echo "Making $reltype for $base_pkg-$ver ..."
 echo " "
-echo "OK?  ctl-c to stop"
-read a
+#echo "OK?  ctl-c to stop"
+#read a
 
-git tag -d ${fulltag} 2>/dev/null 1>/dev/null
+git tag -d ${fulltag}  2>/dev/null 1>/dev/null
 echo "Creating new tag -- $fulltag"
 git tag $fulltag
-check_return_code "$0: Non-zero return status from Git"
+if [ $? != 0 ] ; then
+  echo " "
+  echo "Non-zero return status from Git"
+  echo " "
+  exit 1
+fi
 echo "Create Tag $fulltag done"
 cd ${cwd}
 rm -rf $base_pkg-$ver $base_pkg-$ver.tar.gz $base_pkg-$ver.tar.gz.sig
 rm -rf $fulltag
 cd ${src}
 git archive --format=tar --prefix=$base_pkg-$ver/ $fulltag | gzip >${cwd}/$base_pkg-$ver.tar.gz
-check_return_code "$0: Non-zero return status from Git"
+if [ $? != 0 ] ; then
+  echo " "
+  echo "Non-zero return status from Git"
+  echo " "
+  exit 1
+fi
 echo "Exported release into ${cwd}/$base_pkg-$ver.tar.gz"
 cd ${cwd}
 tar xfz $base_pkg-$ver.tar.gz 
@@ -85,8 +109,8 @@ ls -l $base_pkg-$ver.tar.*
 if [ a$push != ano ]; then
    cd ${src}
    git push ${remote} ${branch}
-#   git push ${remote} tag ${fulltag}
-   echo "Pushed ${remote}"
+   git push ${remote} tag ${fulltag}
+   echo "Pushed ${remote} and push tag ${fulltag}"
 fi
 
 cd ${src}
@@ -94,4 +118,3 @@ git checkout ${current}
 
 cd ${bsrc}
 git checkout ${bcurrent}
-exit 0
diff --git a/src/cats/drop_mysql_database.in b/src/cats/drop_mysql_database.in
--- a/src/cats/drop_mysql_database.in
+++ b/src/cats/drop_mysql_database.in
@@ -3,19 +3,15 @@
 # shell script to drop Bacula database(s)
 #
 
-bindir=@SQL_BINDIR@
+bindir=@MYSQL_BINDIR@
 db_name=@db_name@
 
-if test xmysql = x@DB_TYPE@ ; then 
-  $bindir/mysql $* -f <<END-OF-DATA
-    DROP DATABASE ${db_name};
+$bindir/mysql $* -f <<END-OF-DATA
+  DROP DATABASE ${db_name};
 END-OF-DATA
-  if test $? -eq 0 ; then
-    echo "Drop of ${db_name} database succeeded."
-  else
-    echo "Drop of ${db_name} database failed."
-  fi
+if test $? -eq 0 ; then
+  echo "Drop of ${db_name} database succeeded."
 else
-  echo "Bacula is not configured for a MySQL database."
+  echo "Drop of ${db_name} database failed."
 fi
 exit 0
